Project/Blood_bank/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from Blood_bank.config import Config

app = Flask(__name__)

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
mail = Mail()


app.config.from_object(Config)

db.init_app(app)
bcrypt.init_app(app)
login_manager.init_app(app)
mail.init_app(app)


from Blood_bank.main.routes import main
from Blood_bank.app_admin.routes import app_admin
from Blood_bank.bloodbank_admin.routes import bloodbank_admin
from Blood_bank.app_users.routes import users
from Blood_bank.bloodbanks.routes import bloodbanks
from Blood_bank.errors.handlers import errors

app.register_blueprint(main)
app.register_blueprint(app_admin)
app.register_blueprint(bloodbank_admin)
app.register_blueprint(users)
app.register_blueprint(bloodbanks)
app.register_blueprint(errors)

Project/Blood_bank/app_admin/routes.py
from flask import Blueprint, abort, render_template, flash, redirect, url_for
from flask_login import login_user, current_user, logout_user, login_required
from Blood_bank.app_admin.forms import BloodbankRegistrationForm
from Blood_bank.app_admin.utils import send_bloodbank_registration_email
from Blood_bank import db
from Blood_bank.models import Bloodbank
import requests
import phonenumbers

app_admin = Blueprint('app_admin', __name__)

@app_admin.route("/register_bloodbank", methods=['GET', 'POST'])
@login_required
def register_bloodbank():
	if current_user.role != 'app_admin':
		abort(403)
	form = BloodbankRegistrationForm()
	if form.validate_on_submit():
		contact_no = phonenumbers.parse(form.contact_no.data, "IN")
		contact_no = phonenumbers.format_number(contact_no, phonenumbers.PhoneNumberFormat.E164)
		loc_det = requests.get('https://maps.googleapis.com/maps/api/geocode/json?address='\
							 + form.address.data\
							 + '&key=AIzaSyDEVlxGElqrqiRf74X3Ii-E2eF2S-TJVPY').json()
		lat = float(loc_det['results'][0]['geometry']['location']['lat'])
		lng = float(loc_det['results'][0]['geometry']['location']['lng'])
		bloodbank = Bloodbank(name=form.name.data,\
							  address=form.address.data,\
							  contact_no=contact_no,\
							  email=form.email.data,\
							  latitude=lat,\
							  longitude=lng,\
							  geom='SRID=4326; POINT(' + str(lng) + ' ' + str(lat) + ')')
		db.session.add(bloodbank)
		db.session.commit()
		send_bloodbank_registration_email(form.admin_name.data,\
											form.admin_email.data,\
											form.admin_contact_no.data,\
											"bloodbank_admin",\
											bloodbank.id)
		flash('Email has been sent with instructions to register', 'info')
		return redirect(url_for('main.home'))
	return render_template("register_bloodbank.html", title='Register Bloodbank', form=form)

Project/Blood_bank/app_users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
import phonenumbers
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from Blood_bank import db, bcrypt
from Blood_bank.models import App_user, Bloodbank, Request
from Blood_bank.app_users.forms import (EmailRegistrationForm, RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm, RequestBloodForm)
from Blood_bank.app_users.utils import save_picture, send_reset_email, send_registration_email, send_request
from datetime import datetime, date
import pytz
from geoalchemy2.functions import ST_Distance, ST_SetSRID, ST_Point

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register_email():
	form = EmailRegistrationForm()
	if form.validate_on_submit():
		send_registration_email(form.email.data)
		flash('Email has been sent with instructions to register', 'info')
		return redirect(url_for('users.login'))
	return render_template("register_email.html", title='Register', form=form)

@users.route("/register/<token>", methods=['GET', 'POST'])
def register(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		s = Serializer(current_app.config['SECRET_KEY'])
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		contact_no = phonenumbers.parse(form.contact_no.data, "IN")
		contact_no = phonenumbers.format_number(contact_no, phonenumbers.PhoneNumberFormat.E164)
		user = App_user(name=form.name.data, email=s.loads(token)['email_id'], password=hashed_password, contact_no=contact_no)
		db.session.add(user)
		db.session.commit()
		flash(f'Account created for {form.name.data}!', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title="Register", form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = App_user.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Login failed! Please check email and password', 'danger')
	return render_template('login.html', title="Login", form=form)


@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.name = form.name.data
		current_user.email = form.email.data
		contact_no = phonenumbers.parse(form.contact_no.data, "IN")
		contact_no = phonenumbers.format_number(contact_no, phonenumbers.PhoneNumberFormat.E164)
		current_user.contact_no = contact_no
		db.session.commit()
		flash('Your account has been updated', 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.name.data = current_user.name
		form.email.data = current_user.email
		form.contact_no.data = current_user.contact_no
	image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	return render_template('account.html', title="Account", image_file=image_file, form=form)	

# @users.route("/user/<string:username>")
# def user_posts(username):
# 	page = request.args.get('page', 1, type=int)
# 	user = User.query.filter_by(username=username).first_or_404()
# 	posts = Post.query.filter_by(author=user)\
# 		.order_by(Post.date_posted.desc())\
# 		.paginate(page=page, per_page=5)
# 	return render_template("user_posts.html", posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		send_reset_email(current_user)
		flash('Email has been sent with instructions to reset your password', 'info')
		return redirect(url_for('users.login'))
		# return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = App_user.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('Email has been sent with instructions to reset your password', 'info')
		return redirect(url_for('users.login'))
	return render_template("reset_request.html", title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = App_user.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash(f'Your password has been updated successfully!', 'success')
		return redirect(url_for('users.login'))
	return render_template("reset_token.html", title='Reset Password', form=form)

@users.route("/request_blood", methods=['GET', 'POST'])
@login_required
def request_blood():
	form = RequestBloodForm()
	if form.validate_on_submit():
		req = Request(user_id=current_user.id,\
						  date=datetime.now(pytz.timezone('Asia/Kolkata')),\
						  blood_group=form.blood_group.data,\
						  units=form.units.data)
		# bloodbank.stats.edit(str(form.blood_group.data), int(form.units.data)*(-1))
		db.session.add(req)
		db.session.commit()
		latitude = request.args.get('latitude', 0, type=float)
		longitude = request.args.get('longitude', 0, type=float)
		blood_banks = Bloodbank.query\
						.order_by(ST_Distance(Bloodbank.geom, ST_SetSRID(ST_Point(longitude, latitude), 4326)).asc())\
						.limit(5)
		email_list = list()
		for bloodbank in blood_banks:
			email_list.append(str(bloodbank.email))
		send_request(email_list, form.blood_group.data, form.units.data, current_user)
		msg = 'Request Sent!'
		flash(msg, 'success')
		return redirect(url_for('main.home'))
	return render_template("request_blood.html", title='Request Blood', form=form)

Project/Blood_bank/bloodbank_admin/routes.py
from flask import Blueprint, abort, render_template, flash, redirect, url_for, current_app, request
from flask_login import login_user, current_user, logout_user, login_required
from Blood_bank.bloodbank_admin.forms import AdminRegistrationForm, UpdateAvailabilityForm, ReceivedBloodForm, UtilisedBloodForm
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from Blood_bank import db, bcrypt
from Blood_bank.models import App_user, Bloodbank, Bloodbank_stats, Donor, Donation, Utilisation
import phonenumbers
from datetime import datetime, date
import pytz

bloodbank_admin = Blueprint('bloodbank_admin', __name__)

@bloodbank_admin.route("/register_bloodbank/<token>", methods=['GET', 'POST'])
def register_admin(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = AdminRegistrationForm()
	if form.validate_on_submit():
		s = Serializer(current_app.config['SECRET_KEY'])
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		contact_no = phonenumbers.parse(s.loads(token)['contact_no'], "IN")
		contact_no = phonenumbers.format_number(contact_no, phonenumbers.PhoneNumberFormat.E164)
		user = App_user(name=s.loads(token)['name'],\
						email=s.loads(token)['email_id'],\
						password=hashed_password,\
						contact_no=contact_no,\
						role=s.loads(token)['role'],\
						bloodbank_id=s.loads(token)['bloodbank_id'])
		stats = Bloodbank_stats(bloodbank_id=s.loads(token)['bloodbank_id'],\
								a_positive=0,\
								a_negative=0,\
								b_positive=0,\
								b_negative=0,\
								ab_positive=0,\
								ab_negative=0,\
								o_positive=0,\
								o_negative=0,)
								# date=datetime.now(pytz.timezone('Asia/Kolkata')))
		db.session.add(stats)
		db.session.add(user)
		db.session.commit()
		msg = 'Account created for ' + s.loads(token)['name'] + '!'
		flash(msg, 'success')
		return redirect(url_for('users.login'))
	return render_template('register_admin.html', title="Register Admin", form=form)

@bloodbank_admin.route("/update-availability", methods=['GET', 'POST'])
@login_required
def blood_availability():
	if current_user.role!='bloodbank_admin':
		abort(403)
	form = UpdateAvailabilityForm()
	bloodbank = Bloodbank.query.get(current_user.bloodbank_id)
	if form.validate_on_submit():
		bloodbank.stats.a_positive = form.a_positive.data
		bloodbank.stats.a_negative = form.a_negative.data
		bloodbank.stats.b_positive = form.b_positive.data
		bloodbank.stats.b_negative = form.b_negative.data
		bloodbank.stats.ab_positive = form.ab_positive.data
		bloodbank.stats.ab_negative = form.ab_negative.data
		bloodbank.stats.o_positive = form.o_positive.data
		bloodbank.stats.o_negative = form.o_negative.data
		db.session.commit()
		msg = 'Blood Availability has been updated successfully!'
		flash(msg, 'success')
		return redirect(url_for('bloodbanks.bloodbank', bloodbank_id=bloodbank.id))
	elif request.method=='GET':
		# stats = Bloodbank_stats.query.filter_by(bloodbank_id=bloodbank.id).order_by(Bloodbank_stats.date.desc()).first()
		stats = Bloodbank_stats.query.get(bloodbank.id)
		if stats:
			form.a_positive.data = stats.a_positive
			form.a_negative.data = stats.a_negative
			form.b_positive.data = stats.b_positive
			form.b_negative.data = stats.b_negative
			form.ab_positive.data = stats.ab_positive
			form.ab_negative.data = stats.ab_negative
			form.o_positive.data = stats.o_positive
			form.o_negative.data = stats.o_negative
	return render_template('update_availability.html', title="Blood Availability", form=form)


@bloodbank_admin.route("/update-received-blood", methods=['GET', 'POST'])
@login_required
def received_blood():
	if current_user.role!='bloodbank_admin':
		abort(403)
	form = ReceivedBloodForm()
	bloodbank = Bloodbank.query.get(current_user.bloodbank_id)
	if form.validate_on_submit():
		donor = Donor.query.filter_by(email=form.email.data).first()
		if donor is None:
			donor = Donor(name=form.name.data,\
						  email=form.email.data,\
						  contact_no=form.contact_no.data,\
						  blood_group=form.blood_group.data,\
						  last_donation=date.today())
			db.session.add(donor)
			db.session.commit()
		donation = Donation(donor_id=donor.id,\
							bloodbank_id=bloodbank.id,\
							date=date.today(),\
							units=form.units.data)
		bloodbank.stats.edit(str(form.blood_group.data), int(form.units.data))
		db.session.add(donation)
		db.session.commit()
		msg = 'Donation Added!'
		return redirect(url_for('bloodbanks.bloodbank', bloodbank_id=bloodbank.id))
	return render_template('received_blood.html', title="Received Blood", form=form)

@bloodbank_admin.route("/update-utilised-blood", methods=['GET', 'POST'])
@login_required
def utilised_blood():
	if current_user.role!='bloodbank_admin':
		abort(403)
	form = UtilisedBloodForm()
	bloodbank = Bloodbank.query.get(current_user.bloodbank_id)
	if form.validate_on_submit():
		# donor = Donor.query.filter_by(email=form.email.data).first()
		# if donor is None:
		# 	donor = Donor(name=form.name.data,\
		# 				  email=form.email.data,\
		# 				  contact_no=form.contact_no.data,\
		# 				  blood_group=form.blood_group.data,\
		# 				  last_donation=date.today())
		# 	db.session.add(donor)
		# 	db.session.commit()
		utilisation = Utilisation(bloodbank_id=bloodbank.id,\
								  date_time=datetime.now(pytz.timezone('Asia/Kolkata')),\
								  blood_group=form.blood_group.data,\
								  units=form.units.data
								  )
		bloodbank.stats.edit(str(form.blood_group.data), int(form.units.data)*(-1))
		db.session.add(utilisation)
		db.session.commit()
		msg = 'Utilisation Added!'
		return redirect(url_for('bloodbanks.bloodbank', bloodbank_id=bloodbank.id))
	return render_template('utilised_blood.html', title="Received Blood", form=form)

Project/Blood_bank/main/routes.py
import io
from flask import Blueprint, Response, render_template, abort
from flask_login import login_required, current_user
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
# from Blood_bank import db
from Blood_bank.main.utils import create_bar#, create_line
from Blood_bank.models import Donation, Donor, Utilisation
from sqlalchemy import func

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
	return render_template('home.html', title='Blood Buddy')


# @main.route("/total-units-donated.png")
# @login_required
# def total_donation_line_plot():
# 	if current_user.role!='app_admin':
# 		abort(403)
# 	# donation = Donation.query.all()
# 	donation = db.session.query(Donation.date, func.sum(Donation.units)).group_by(Donation.date)
# 	dates = list()
# 	units = list()
# 	for row in donation:
# 		dates.append(row.date)
# 		units.append(row[1])
# 	fig = create_line(dates, units, 'Total Donations', 'Time', 'Units')
# 	output = io.BytesIO()
# 	FigureCanvas(fig).print_png(output)
# 	return Response(output.getvalue(), mimetype='image/png')



@main.route("/donations.png")
@login_required
def total_donation_bar_plot():
	if current_user.role!='app_admin':
		abort(403)
	received = {'A+':0, 'A-':0,\
				'B+':0, 'B-':0,\
				'AB+':0, 'AB-':0,\
				'O+':0, 'O-':0}
	donation = Donation.query.all()
	for row in donation:
		donor = Donor.query.get(row.donor_id)
		bg = str(donor.blood_group)
		received[bg] = received[bg] + int(row.units)
	fig = create_bar(list(received.keys()), list(received.values()), 'Total Donations', 'Blood Group', 'Units')
	output = io.BytesIO()
	FigureCanvas(fig).print_png(output)
	return Response(output.getvalue(), mimetype='image/png')

@main.route("/utilisation.png")
@login_required
def total_utilisation_bar_plot():
	if current_user.role!='app_admin':
		abort(403)
	utilised = {'A+':0, 'A-':0,\
				'B+':0, 'B-':0,\
				'AB+':0, 'AB-':0,\
				'O+':0, 'O-':0}
	# utilisation = Utilisation.query.filter(cast(Utilisation.date_time, Date)==date.today()).filter_by(bloodbank_id=bloodbank_id).all()
	utilisation = Utilisation.query.all()
	for row in utilisation:
		bg = str(row.blood_group)
		utilised[bg] = utilised[bg] + int(row.units)
	fig = create_bar(list(utilised.keys()), list(utilised.values()), "Total Utilisation", 'Blood Group', 'Units')
	output = io.BytesIO()
	FigureCanvas(fig).print_png(output)
	return Response(output.getvalue(), mimetype='image/png')

Project/Blood_bank/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col">
		<h3>Motivation</h3><br>
		<h5 align="justify">Today, most medical care depends on a steady supply of blood from donors, as one in seven people entering the hospital need blood. For Moffitt, as cancer care increases, so does the demand for blood and platelet donations. An adequate amount of blood is needed in all health care facilities to meet the urgent need for patients facing trauma and other lifesaving procedures, such as blood transfusions – which saves millions of lives each year.</h5><br>
		<h5 align="justify">India fell short of 1.9 million units of blood in 2016-17–equivalent to 60 tankers–that could have aided more than 320,000 heart surgeries or 49,000 organ transplants, according to official data.</h5> <br>
			<img src="https://www.centurypa.com/images/blog/Blood%20donation.jpg" style="width:400px;height:300px;"><br>
		<h5 align="justify">This is an increase from a shortage of 1.1 million units or 35 tankers in 2015-16, when India had fallen 9% short of its 12 million target.</h5><br>
			<img src="https://cdn.dnaindia.com/sites/default/files/styles/full/public/2019/01/29/783772-blood-donation-camp-03.jpg" style="width:600px;height:300px;"><br>

		<h3>Objectives</h3><br>
		<h5>- Appropriate management of existing resources.<br>
			- Digital awareness about blood donation camps for better reach.<br>
			- Availability of proper management system for effective planning.<br>
		</h5><br>
	</div>
	</div>
</div>

	{% if current_user.role=='app_admin' %}
		<img src="{{ url_for('main.total_donation_bar_plot') }}" alt="my plot">
		<img src="{{ url_for('main.total_utilisation_bar_plot') }}" alt="my plot">
	{% endif %}
{% endblock content %}

Project/Blood_bank/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

	{% if title %}
		<title>Blood Bank Management System- {{ title }}</title>
	{% else %}
		<title>Blood Bank Management System</title>
	{% endif %}
</head>

<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="/"><img src="https://www.flaticon.com/svg/vstatic/svg/3259/3259860.svg?token=exp=1620309898~hmac=aff7486e72ad02e2da12043b6480fd6e" width="30" height="30" class="d-inline-block align-top" >Blood Bank Management System</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
	          {% if current_user.role not in ['app_admin', 'bloodbank_admin'] %}
	          	<a onclick="getLocation()" class="nav-item nav-link" href="#">Bloodbanks Nearby</a>
	          {% endif %}
	          {% if current_user.is_authenticated and current_user.role=='app_user'%}
	          	<a onclick="getLoc()" class="nav-item nav-link" href="#">Request Blood</a>
	          {% endif %}
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	          {% if current_user.is_authenticated %}
	          	{% if current_user.role=='app_admin' %}
	          		<a class="nav-item nav-link" href="{{ url_for('app_admin.register_bloodbank') }}">Add Bloodbank</a>
	          	{% endif %}
	          	{% if current_user.role=='bloodbank_admin' %}
	          		<div class="dropdown">
					  <a class="nav-item nav-link dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">Update</a> 
					  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					    <a class="dropdown-item" href="{{ url_for('bloodbank_admin.received_blood') }}">Received Donation</a>
					    <a class="dropdown-item" href="{{ url_for('bloodbank_admin.utilised_blood') }}">Utilized Blood</a>
					    <a class="dropdown-item" href="{{ url_for('bloodbank_admin.blood_availability') }}">Availability</a>
					  </div>
					</div>
	          	{% endif %}
	            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
	            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
	          {% else %}
	            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
	            <a class="nav-item nav-link" href="{{ url_for('users.register_email') }}">Register</a>
	          {% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>

	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	      {% with messages = get_flashed_messages(with_categories=true) %}
	    	{% if messages %}
	          {% for category, message in messages %}
	    		<div class="alert alert-{{ category }}">
	    	 	  {{ message }}
	    		</div>
	          {% endfor %}
	    	{% endif %}
	      {% endwith %}
	      {% block content %}{% endblock %}
	    	
	    </div>
	  </div>
	</main>

	<!-- Optional JavaScript -->
	<script>
		function showPosition(position) {
		  var lat = position.coords.latitude;
		  var long = position.coords.longitude;
		  var param = { "page":"1", "latitude":lat, "longitude":long };
		  window.location.href = "/bloodbanks_nearby?latitude=" + lat + "&longitude=" + long;
		}

		function getLocation() {
		  if (navigator.geolocation) {
		    navigator.geolocation.getCurrentPosition(showPosition, showError);
		  } else { 
		    x.innerHTML = "Geolocation is not supported by this browser.";
		  }
		}

		function switchTab(position) {
		  var lat = position.coords.latitude;
		  var long = position.coords.longitude;
		  window.location.href = "/request_blood?latitude=" + lat + "&longitude=" + long;	
		}

		function getLoc() {
		  if (navigator.geolocation) {
		    navigator.geolocation.getCurrentPosition(switchTab, showError);
		  } else { 
		    x.innerHTML = "Geolocation is not supported by this browser.";
		  }
		}

		function showError(error) {
		  switch(error.code) {
		    case error.PERMISSION_DENIED:
		      x.innerHTML = "User denied the request for Geolocation."
		      break;
		    case error.POSITION_UNAVAILABLE:
		      x.innerHTML = "Location information is unavailable."
		      break;
		    case error.TIMEOUT:
		      x.innerHTML = "The request to get user location timed out."
		      break;
		    case error.UNKNOWN_ERROR:
		      x.innerHTML = "An unknown error occurred."
		      break;
		  }
		}
	</script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

Project/Blood_bank/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}	
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Don't have an account? <a class="ml-2" href="{{ url_for('users.register_email') }}">Sign Up Now</a>
		</small>
	</div>
{% endblock content %}